<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>对账及询证函邮件工具_便携版</AssemblyName>
    <RootNamespace>MailToolPortable</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.Office.Interop.Excel" />
    <Reference Include="Microsoft.Office.Interop.Outlook" />
  </ItemGroup>
</Project>