<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>对账及询证函邮件工具_便携版</AssemblyName>
    <RootNamespace>MailToolPortable</RootNamespace>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>